apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
    tls: default-server-secret
    hosts:
    - xyz.com
  selector:
    app: nginx-ingress-1
    tls: default-server-secret-1
    hosts:
    - xyz.com/abc
    